In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
df1= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-1996-to-31-12-1997.csv')

In [7]:
df2= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-1998-to-31-12-1999.csv')

In [8]:
df3= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2000-to-31-12-2001.csv')

In [9]:
df4= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2002-to-31-12-2003.csv')

In [10]:
df5= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2004-to-31-12-2005.csv')

In [11]:
df6= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2006-to-31-12-2007.csv')

In [12]:
df7= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2008-to-31-12-2009.csv')

In [13]:
df8= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2010-to-31-12-2011.csv')

In [14]:
df9= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2012-to-31-12-2013.csv')

In [15]:
df10= pd.read_csv('Quote-Equity-TATAMOTORS-EQ-01-01-2014-to-31-12-2015.csv')

In [16]:
frames = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10]

In [17]:
frames1 = [df1,df2,df3]

In [18]:
result = pd.concat(frames1)

In [19]:
result.columns

Index(['Date ', 'series ', 'OPEN ', 'HIGH ', 'LOW ', 'PREV. CLOSE ', 'ltp ',
       'close ', 'vwap ', '52W H ', '52W L ', 'VOLUME ', 'VALUE ',
       'No of trades '],
      dtype='object')

In [20]:
result.head()

Date  series    OPEN    HIGH     LOW  PREV. CLOSE  ltp   close   \
0  31-Dec-1997      EQ  296.25  305.00  292.25       295.50    -  297.75   
1  30-Dec-1997      EQ  304.05  313.40  292.05       300.60    -  295.50   
2  29-Dec-1997      EQ  277.90  303.75  275.30       276.10    -  300.60   
3  26-Dec-1997      EQ  274.00  278.95  272.10       273.50    -  276.10   
4  24-Dec-1997      EQ  277.00  277.40  268.15       281.60    -  273.50   

    vwap   52W H   52W L   VOLUME             VALUE   No of trades   
0  299.81  469.55  253.15  1350100    404,774,877.50            NaN  
1  305.03  469.55  253.15  3409150  1,039,903,982.50            NaN  
2  289.64  469.55  253.15  2232600    646,655,395.00            NaN  
3  275.14  469.55  253.15   657350    180,866,500.00            NaN  
4  271.56  469.55  253.15   716250    194,503,812.50            NaN

In [21]:
result['Date '] = pd.to_datetime(result['Date '], errors='coerce')

In [22]:
result = result.sort_values(by='Date ')

In [23]:
result

Date  series    OPEN    HIGH     LOW  PREV. CLOSE    ltp   close   \
493 1996-01-01      EQ  378.00  380.00  377.50       379.80      -  380.00   
492 1996-01-02      EQ  380.00  383.90  376.00       380.00      -  377.80   
491 1996-01-03      EQ  377.80  380.00  376.25       377.80      -  376.55   
490 1996-01-04      EQ  376.55  377.00  371.50       376.55      -  373.70   
489 1996-01-05      EQ  373.70  374.80  371.00       373.70      -  372.35   
..         ...     ...     ...     ...     ...          ...    ...     ...   
4   2001-12-24      EQ   96.40   98.00   94.00         97.5   96.2   95.85   
3   2001-12-26      EQ   97.00   99.45   95.00        95.85     96   96.40   
2   2001-12-27      EQ   97.50   97.50   93.15         96.4  95.15   94.55   
1   2001-12-28      EQ   93.50   97.10   93.00        94.55  96.45   96.50   
0   2001-12-31      EQ   98.85  100.35   96.50         96.5    100   99.85   

      vwap   52W H  52W L   VOLUME          VALUE   No of trades   
493  378.94       -      -     7800   2,955,715.00            NaN  
492  380.09       -      -    19350   7,354,800.00            NaN  
491  378.43       -      -     5700   2,157,065.00            NaN  
490  374.62       -      -    20100   7,529,930.00            NaN  
489  372.60       -      -    12000   4,471,250.00            NaN  
..      ...     ...    ...      ...            ...            ...  
4     95.52  114.35  57.55   154698  14,776,500.70            NaN  
3     96.98  114.35  57.55   255411  24,770,390.70            NaN  
2     94.70  114.35  57.55   227696  21,561,884.10            NaN  
1     94.99  114.35  57.55   239782  22,777,068.80            NaN  
0     98.76  114.35  57.55   329319  32,522,360.40            NaN  

[1496 rows x 14 columns]

In [24]:
df=result[['close ']]

In [25]:
df.head()

close 
493  380.00
492  377.80
491  376.55
490  373.70
489  372.35

In [ ]:
df['close '] = df['close '].str.replace(',', '')

In [27]:
df['close '] = df['close '].astype(float)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1496 entries, 493 to 0
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   close   1496 non-null   float64
dtypes: float64(1)
memory usage: 23.4 KB


In [29]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
df=scaler.fit_transform(np.array(df).reshape(-1,1))

In [30]:
training_size=int(len(df)*0.65)
test_size= len(df)-training_size
train_data,test_data= df[0:training_size,:],df[training_size:len(df1),:1]

In [31]:
def create_dataset(dataset, timestep=1):
    dataX,dataY=[],[]
    for i in range (len(dataset)-timestep-1):
        a = dataset[i:(i+timestep),0]
        dataX.append(a)
        dataY.append(dataset[i+timestep,0])
    return np.array(dataX),np.array(dataY)

In [32]:
timestep=200
xtrain,ytrain=create_dataset(train_data,timestep)
xtest,ytest=create_dataset(test_data,timestep)

In [33]:
print(xtrain)

[[0.64485043 0.64043365 0.63792411 ... 0.73087733 0.72555712 0.73750251]
 [0.64043365 0.63792411 0.63220237 ... 0.72555712 0.73750251 0.72555712]
 [0.63792411 0.63220237 0.62949207 ... 0.73750251 0.72555712 0.7229472 ]
 ...
 [0.24653684 0.25336278 0.28167035 ... 0.3381851  0.33396908 0.33467175]
 [0.25336278 0.28167035 0.29371612 ... 0.33396908 0.33467175 0.33507328]
 [0.28167035 0.29371612 0.29953825 ... 0.33467175 0.33507328 0.33517366]]


In [34]:
print(ytrain)

[0.72555712 0.7229472  0.72364987 0.75155591 0.77253564 0.73910861
 0.7462357  0.74794218 0.71832965 0.71451516 0.71441478 0.70106404
 0.67175266 0.67396105 0.68691026 0.6942381  0.68179081 0.7256575
 0.72234491 0.6980526  0.70467778 0.70096366 0.68851636 0.66030917
 0.64023288 0.58773339 0.58913873 0.57157197 0.52499498 0.51887171
 0.52027705 0.47791608 0.46928328 0.47610922 0.5011042  0.50732785
 0.49357559 0.49598474 0.53764304 0.52047782 0.51345111 0.55741819
 0.57950211 0.56866091 0.56123268 0.57137121 0.56313993 0.55812086
 0.58191126 0.55922506 0.6055009  0.59817306 0.60178679 0.59164826
 0.57247541 0.58391889 0.5817105  0.59977916 0.59064445 0.57759486
 0.62617948 0.59174864 0.57568761 0.55400522 0.55430636 0.55219835
 0.55430636 0.59225055 0.59054407 0.57829753 0.55370408 0.52629994
 0.49979924 0.49939771 0.51003814 0.519474   0.52389078 0.52188316
 0.54768119 0.55069263 0.55239912 0.5692632  0.57809677 0.56615138
 0.57528609 0.5703674  0.57177274 0.55701666 0.56203574 0.55912

In [35]:
#reshape input to be [samples, timesteps, features] which is required for LSTM
xtrain=xtrain.reshape(xtrain.shape[0], xtrain.shape[1], 1)
xtest=xtest.reshape(xtest.shape[0], xtrain.shape[1], 1)

In [36]:
xtrain.shape

(771, 200, 1)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

In [ ]:
#vanilla LSTM
model=Sequential()
model.add(LSTM(50, activation='relu', input_shape=(200,1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [38]:
#stacked LSTM
model=Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(200,1)))
model.add(LSTM(50, return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))
model.compile(loss="mean_squared_error",optimizer="adam")

In [39]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 200, 50)           10400     
_________________________________________________________________
lstm_1 (LSTM)                (None, 200, 50)           20200     
_________________________________________________________________
lstm_2 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 50,851
Trainable params: 50,851
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.fit(xtrain,ytrain,validation_data=(xtest,ytest),epochs=100,batch_size=64,verbose=1)

Epoch 1/100
13/13 [==============================] - 55s 1s/step - loss: 0.0808
Epoch 2/100
13/13 [==============================] - 10s 675ms/step - loss: 0.0115
Epoch 3/100
13/13 [==============================] - 6s 492ms/step - loss: 0.0049
Epoch 4/100
13/13 [==============================] - 7s 497ms/step - loss: 0.0037
Epoch 5/100
13/13 [==============================] - 6s 473ms/step - loss: 0.0027
Epoch 6/100
13/13 [==============================] - 6s 472ms/step - loss: 0.0026
Epoch 7/100
13/13 [==============================] - 6s 467ms/step - loss: 0.0026
Epoch 8/100
13/13 [==============================] - 6s 467ms/step - loss: 0.0026
Epoch 9/100
13/13 [==============================] - 6s 494ms/step - loss: 0.0027
Epoch 10/100
13/13 [==============================] - 6s 489ms/step - loss: 0.0026
Epoch 11/100
13/13 [==============================] - 7s 502ms/step - loss: 0.0023
Epoch 12/100
13/13 [==============================] - 7s 523ms/step - loss: 0.0023
Epoch 13/100
1

13/13 [==============================] - 6s 449ms/step - loss: 4.4790e-04
Epoch 98/100
13/13 [==============================] - 6s 454ms/step - loss: 5.2378e-04
Epoch 99/100
13/13 [==============================] - 6s 458ms/step - loss: 4.0474e-04
Epoch 100/100
13/13 [==============================] - 8s 586ms/step - loss: 5.0589e-04


In [218]:
testf1= pd.read_csv('Quote-Equity-MARUTI-EQ-01-01-2003-to-31-12-2004.csv')

In [219]:
testf2= pd.read_csv('Quote-Equity-MARUTI-EQ-01-01-2005-to-31-12-2006.csv')

In [220]:
testf3= pd.read_csv('Quote-Equity-MARUTI-EQ-01-01-2007-to-31-12-2008.csv')

In [221]:
tframes1 = [testf1,testf2]

In [222]:
tresult = pd.concat(tframes1)

In [223]:
tresult.columns

Index(['Date', 'series', 'OPEN', 'HIGH ', 'LOW ', 'PREV. CLOSE ', 'ltp ',
       'close ', 'vwap ', '52W H ', '52W L ', 'VOLUME ', 'VALUE ',
       'No of trades ', 'Date ', 'series ', 'OPEN '],
      dtype='object')

In [229]:
testf1['Date'] = pd.to_datetime(testf1['Date'], errors='coerce')

In [230]:
testf1 = testf1.sort_values(by='Date')

In [231]:
tdf=testf1[['close ']]

In [233]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
tdf=scaler.fit_transform(np.array(tdf).reshape(-1,1))

In [234]:
timestep=200
testx,testy=create_dataset(tdf,timestep)

In [235]:
testx.shape   , testy.shape

((177, 200), (177,))

In [236]:
testx=testx.reshape(testx.shape[0], testx.shape[1], 1)

In [237]:
predict=model.predict(testx)

In [243]:
testx.shape

(177, 200, 1)

In [244]:
predict = scaler.inverse_transform(predict)

In [240]:
import math
from sklearn.metrics import mean_absolute_error
math.sqrt(mean_absolute_error(testy,predict))

0.14893393145225026